name: Django                                 

on:
  push:
    branches:                                
      - main

jobs:
  nuclei-scan:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: ${{ secrets.PROD_URL }}
        continue-on-error: true

      - name: GitHub Workflow artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuclei.log
          path: nuclei.log    
